- hosts: app
  become: true
  vars:
    app_jar_s3_bucket: "{{ lookup('env','APP_S3_BUCKET') | default('') }}"
    app_jar_s3_key: "{{ lookup('env','APP_S3_KEY') | default('artifacts/FleetCoreServer.jar') }}"
    rds_endpoint: "{{ lookup('env','RDS_ENDPOINT') | default('') }}"
    rds_port: "{{ lookup('env','RDS_PORT') | default('5432') }}"
    rds_db: "{{ lookup('env','RDS_DB') | default('fleetcore') }}"
    rds_user: "{{ lookup('env','RDS_USER') | default('fleetcore') }}"
  roles:
    - base
    - fleetcore
